from pathlib import Path
import re
import sys


ROOT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("sage_build")
JAVA = ROOT / "app/src/main/java/com/pineapple/sage"


def replace_once(path: Path, old: str, new: str, label: str) -> None:
    text = path.read_text()
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected exactly one match, found {count}")
    path.write_text(text.replace(old, new, 1))


accessibility = JAVA / "SageAccessibilityService.java"
command = JAVA / "SageCommandEngine.java"
voice = JAVA / "SageVoiceService.java"
diagnostics = JAVA / "SageDiagnostics.java"
main = JAVA / "MainActivity.java"
build_gradle = ROOT / "app/build.gradle.kts"

# Numbered overlay: make every lifecycle exit explicit and diagnosable.
replace_once(
    accessibility,
    '''    private static final long NUMBER_OVERLAY_TIMEOUT_MS = 120000L;
    private static final long NUMBER_OVERLAY_EVENT_GRACE_MS = 2500L;''',
    '''    private static final long DEFAULT_NUMBER_OVERLAY_TIMEOUT_MS = 60000L;
    private static final long NUMBER_OVERLAY_EVENT_GRACE_MS = 2500L;
    private static final String NUMBER_OVERLAY_TIMEOUT_KEY = "number_overlay_timeout_ms";''',
    "overlay timeout constants",
)
replace_once(
    accessibility,
    '''    private final Runnable clearNumberOverlayRunnable = this::clearNumberOverlayInternal;''',
    '''    private final Runnable clearNumberOverlayRunnable =
            () -> clearNumberOverlayInternal("timeout", null);''',
    "overlay timeout runnable reason",
)
replace_once(
    accessibility,
    '''    public boolean onUnbind(android.content.Intent intent) {
        clearNumberOverlayInternal();''',
    '''    public boolean onUnbind(android.content.Intent intent) {
        clearNumberOverlayInternal("service_unbind", null);''',
    "overlay unbind reason",
)
replace_once(
    accessibility,
    '''        if (!eventPackage.isEmpty() && eventPackage.equals(getPackageName())) {
            // Accessibility-overlay window notifications are generated by Sage itself.
            return;
        }''',
    '''        if (!eventPackage.isEmpty() && eventPackage.equals(getPackageName())) {
            SageDiagnostics.overlayEvent(
                    this,
                    "ignored_sage_overlay_event",
                    event.getEventType(),
                    eventPackage,
                    event.getWindowId(),
                    SystemClock.uptimeMillis() - numberOverlayShownAtMs
            );
            return;
        }''',
    "ignore and diagnose Sage overlay events",
)
replace_once(
    accessibility,
    '''        if (differentPackage || deliberateMovement) {
            clearNumberOverlayInternal();
        }''',
    '''        if (differentPackage) {
            clearNumberOverlayInternal("package_navigation", event);
        } else if (type == AccessibilityEvent.TYPE_VIEW_CLICKED) {
            clearNumberOverlayInternal("view_clicked", event);
        } else if (type == AccessibilityEvent.TYPE_VIEW_SCROLLED) {
            clearNumberOverlayInternal("view_scrolled", event);
        } else {
            SageDiagnostics.overlayEvent(
                    this,
                    "ignored_content_or_window_churn",
                    type,
                    eventPackage,
                    event.getWindowId(),
                    SystemClock.uptimeMillis() - numberOverlayShownAtMs
            );
        }''',
    "overlay event lifecycle",
)
replace_once(
    accessibility,
    '''    public void onInterrupt() {
        clearNumberOverlayInternal();
    }''',
    '''    public void onInterrupt() {
        clearNumberOverlayInternal("service_interrupt", null);
    }''',
    "overlay interrupt reason",
)
replace_once(
    accessibility,
    '''        service.clearNumberOverlayInternal();
        return service.performGlobalAction(action);''',
    '''        service.clearNumberOverlayInternal("global_action_" + action, null);
        return service.performGlobalAction(action);''',
    "global action reason",
)
replace_once(
    accessibility,
    '''        service.clearNumberOverlayInternal();
        AccessibilityNodeInfo root = service.getRootInActiveWindow();
        AccessibilityNodeInfo scrollable = findScrollable(root);''',
    '''        service.clearNumberOverlayInternal(
                down ? "tablet_scroll_down" : "tablet_scroll_up",
                null
        );
        AccessibilityNodeInfo root = service.getRootInActiveWindow();
        AccessibilityNodeInfo scrollable = findScrollable(root);''',
    "tablet scroll reason",
)
replace_once(
    accessibility,
    '''        service.clearNumberOverlayInternal();
        AccessibilityNodeInfo root = service.getRootInActiveWindow();
        if (root == null) {
            return false;
        }
        String target = requestedText.trim().toLowerCase(Locale.US);''',
    '''        service.clearNumberOverlayInternal("tablet_tap_text", null);
        AccessibilityNodeInfo root = service.getRootInActiveWindow();
        if (root == null) {
            return false;
        }
        String target = requestedText.trim().toLowerCase(Locale.US);''',
    "tap text reason",
)
replace_once(
    accessibility,
    '''        service.clearNumberOverlayInternal();
        AccessibilityNodeInfo root = service.getRootInActiveWindow();
        if (root == null) {
            return false;
        }
        DisplayMetrics metrics = service.getResources().getDisplayMetrics();''',
    '''        service.clearNumberOverlayInternal("tablet_indexed_tap", null);
        AccessibilityNodeInfo root = service.getRootInActiveWindow();
        if (root == null) {
            return false;
        }
        DisplayMetrics metrics = service.getResources().getDisplayMetrics();''',
    "indexed tap reason",
)
replace_once(
    accessibility,
    '''        if (root == null || !service.isOverlayForRoot(root)) {
            service.clearNumberOverlayInternal();
            return false;
        }''',
    '''        if (root == null || !service.isOverlayForRoot(root)) {
            service.clearNumberOverlayInternal("selection_root_invalid", null);
            return false;
        }''',
    "selection invalid reason",
)
replace_once(
    accessibility,
    '''        if (opened) {
            service.clearNumberOverlayInternal();
        }''',
    '''        if (opened) {
            service.clearNumberOverlayInternal("selection_succeeded", null);
        }''',
    "selection success reason",
)
replace_once(
    accessibility,
    '''    public static void clearNumberOverlay() {
        SageAccessibilityService service = instance;
        if (service != null) {
            service.clearNumberOverlayInternal();
        }
    }''',
    '''    public static void clearNumberOverlay() {
        clearNumberOverlay("manual_clear");
    }

    public static void clearNumberOverlay(String reason) {
        SageAccessibilityService service = instance;
        if (service != null) {
            service.clearNumberOverlayInternal(
                    reason == null || reason.trim().isEmpty() ? "manual_clear" : reason,
                    null
            );
        }
    }

    public static void noteHostResumed() {
        SageAccessibilityService service = instance;
        if (service != null && !service.numberedTargets.isEmpty()) {
            SageDiagnostics.overlayEvent(
                    service,
                    "host_activity_resumed_overlay_preserved",
                    -1,
                    service.getPackageName(),
                    service.numberedWindowId,
                    SystemClock.uptimeMillis() - service.numberOverlayShownAtMs
            );
        }
    }''',
    "public overlay clear API",
)
replace_once(
    accessibility,
    '''        service.clearNumberOverlayInternal();
        AccessibilityNodeInfo root = service.getRootInActiveWindow();
        if (root == null) {
            return false;
        }
        AccessibilityNodeInfo target = root.findFocus''',
    '''        service.clearNumberOverlayInternal("tablet_type_text", null);
        AccessibilityNodeInfo root = service.getRootInActiveWindow();
        if (root == null) {
            return false;
        }
        AccessibilityNodeInfo target = root.findFocus''',
    "type text reason",
)
replace_once(
    accessibility,
    '''    ) {
        clearNumberOverlayInternal();
        if (windowManager == null || candidates == null || candidates.isEmpty()) {''',
    '''    ) {
        clearNumberOverlayInternal("overlay_recreated", null);
        if (windowManager == null || candidates == null || candidates.isEmpty()) {''',
    "overlay recreation reason",
)
replace_once(
    accessibility,
    '''            } catch (RuntimeException ignored) {
            }
        }
        if (!numberedTargets.isEmpty()) {
            mainHandler.postDelayed(clearNumberOverlayRunnable, NUMBER_OVERLAY_TIMEOUT_MS);
        }
        return numberedTargets.size();
    }

    private void clearNumberOverlayInternal() {
        mainHandler.removeCallbacks(clearNumberOverlayRunnable);''',
    '''            } catch (RuntimeException error) {
                SageDiagnostics.appendEvent(
                        this,
                        "OVERLAY RENDER",
                        "addView failed: " + error.getClass().getSimpleName()
                );
            }
        }
        if (!numberedTargets.isEmpty()) {
            long timeoutMs = getSharedPreferences("sage_state", Context.MODE_PRIVATE)
                    .getLong(NUMBER_OVERLAY_TIMEOUT_KEY, DEFAULT_NUMBER_OVERLAY_TIMEOUT_MS);
            SageDiagnostics.overlayCreated(
                    this,
                    numberedTargets.size(),
                    numberedPackageName,
                    numberedWindowId,
                    timeoutMs
            );
            if (timeoutMs > 0L) {
                mainHandler.postDelayed(clearNumberOverlayRunnable, timeoutMs);
            }
        }
        return numberedTargets.size();
    }

    private void clearNumberOverlayInternal(String reason, AccessibilityEvent event) {
        mainHandler.removeCallbacks(clearNumberOverlayRunnable);
        if (!numberOverlayViews.isEmpty() || !numberedTargets.isEmpty()) {
            String eventPackage = event == null || event.getPackageName() == null
                    ? ""
                    : event.getPackageName().toString();
            SageDiagnostics.overlayCleared(
                    this,
                    reason,
                    event == null ? -1 : event.getEventType(),
                    eventPackage,
                    event == null ? -1 : event.getWindowId(),
                    numberOverlayShownAtMs <= 0L
                            ? -1L
                            : SystemClock.uptimeMillis() - numberOverlayShownAtMs
            );
        }''',
    "overlay diagnostics and configurable timeout",
)

# Overlay lifetime must not be tied to voice follow-up cancellation or Activity resume.
replace_once(
    command,
    '''    public void cancelFollowUp() {
        pendingAction = "";
        pendingTeachingPhrase = "";
        SageAccessibilityService.clearNumberOverlay();
    }''',
    '''    public void cancelFollowUp() {
        pendingAction = "";
        pendingTeachingPhrase = "";
        SageDiagnostics.appendEvent(
                context,
                "FOLLOW-UP",
                "Pending voice follow-up cancelled; numbered overlay preserved"
        );
    }''',
    "decouple overlay from follow-up",
)
replace_once(
    main,
    '''        SageAccessibilityService.clearNumberOverlay();
        refreshStatus(null);''',
    '''        SageAccessibilityService.noteHostResumed();
        refreshStatus(null);''',
    "preserve overlay on activity resume",
)
replace_once(
    main,
    '''            SageAccessibilityService.clearNumberOverlay();
            Toast.makeText(this, "Screen numbers cleared.", Toast.LENGTH_LONG).show();''',
    '''            SageAccessibilityService.clearNumberOverlay("settings_manual_clear");
            Toast.makeText(this, "Screen numbers cleared.", Toast.LENGTH_LONG).show();''',
    "settings manual overlay clear",
)
replace_once(
    command,
    '''                SageAccessibilityService.clearNumberOverlay();
                return Result.quiet("Screen numbers cleared.");''',
    '''                SageAccessibilityService.clearNumberOverlay("voice_cancel_numbers");
                return Result.quiet("Screen numbers cleared.");''',
    "voice follow-up clear reason",
)
replace_once(
    command,
    '''            SageAccessibilityService.clearNumberOverlay();
            return Result.quiet("Numbers cleared.");''',
    '''            SageAccessibilityService.clearNumberOverlay("voice_manual_clear");
            return Result.quiet("Numbers cleared.");''',
    "voice manual clear reason",
)

# Diagnostics for overlay and recognition decisions.
replace_once(
    diagnostics,
    '''    public static void brainRequest(Context context, String detail) {
        increment(context, KEY_BRAIN_REQUESTS);
        appendEvent(context, "BRAIN", detail);
    }

    public static void appendEvent''',
    '''    public static void brainRequest(Context context, String detail) {
        increment(context, KEY_BRAIN_REQUESTS);
        appendEvent(context, "BRAIN", detail);
    }

    public static void overlayCreated(
            Context context,
            int count,
            String packageName,
            int windowId,
            long timeoutMs
    ) {
        appendEvent(
                context,
                "OVERLAY CREATED",
                "count=" + count
                        + " package=" + safe(packageName)
                        + " window=" + windowId
                        + " timeoutMs=" + timeoutMs
        );
    }

    public static void overlayCleared(
            Context context,
            String reason,
            int eventType,
            String packageName,
            int windowId,
            long elapsedMs
    ) {
        appendEvent(
                context,
                "OVERLAY CLEARED",
                "reason=" + safe(reason)
                        + " event=" + eventType
                        + " package=" + safe(packageName)
                        + " window=" + windowId
                        + " elapsedMs=" + elapsedMs
        );
    }

    public static void overlayEvent(
            Context context,
            String reason,
            int eventType,
            String packageName,
            int windowId,
            long elapsedMs
    ) {
        appendEvent(
                context,
                "OVERLAY EVENT",
                "reason=" + safe(reason)
                        + " event=" + eventType
                        + " package=" + safe(packageName)
                        + " window=" + windowId
                        + " elapsedMs=" + elapsedMs
        );
    }

    public static void recognitionDecision(
            Context context,
            String candidates,
            String selected,
            float confidence,
            String normalized,
            String matched,
            String rejection
    ) {
        appendEvent(
                context,
                "RECOGNITION",
                "candidates=" + safe(candidates)
                        + " selected=" + safe(selected)
                        + " confidence=" + confidence
                        + " normalized=" + safe(normalized)
                        + " matched=" + safe(matched)
                        + " rejection=" + safe(rejection)
        );
    }

    public static void memoryEvent(Context context, String detail) {
        appendEvent(context, "MEMORY", detail);
    }

    public static void appendEvent''',
    "overlay and speech diagnostics",
)

# Speech recognition: final results outrank partials, confidence is retained, and retry is bounded.
replace_once(
    voice,
    '''    private static final int MAX_COMMAND_BUSY_RETRIES = 1;''',
    '''    private static final int MAX_COMMAND_BUSY_RETRIES = 1;
    private static final int MAX_COMMAND_QUALITY_RETRIES = 1;
    private static final float LOW_COMMAND_CONFIDENCE = 0.35f;''',
    "speech quality constants",
)
replace_once(
    voice,
    '''    private int commandBusyRetries;
    private long commandSessionGeneration;''',
    '''    private int commandBusyRetries;
    private int commandQualityRetries;
    private long commandSessionGeneration;''',
    "speech quality retry field",
)
replace_once(
    voice,
    '''                    ArrayList<String> combinedChoices = new ArrayList<>();
                    if (choices != null) {
                        for (String choice : choices) {
                            if (choice != null && !combinedChoices.contains(choice)) {
                                combinedChoices.add(choice);
                            }
                        }
                    }
                    for (String partial : partialChoices) {
                        if (partial != null && !combinedChoices.contains(partial)) {
                            combinedChoices.add(partial);
                        }
                    }
                    String candidate = chooseBestCandidate(combinedChoices);
                    destroyCommandRecognizer();
                    commandBusyRetries = 0;
                    if (!candidate.isEmpty()) {
                        handleCommand(candidate);''',
    '''                    ArrayList<String> finalChoices = new ArrayList<>();
                    if (choices != null) {
                        for (String choice : choices) {
                            if (choice != null && !choice.trim().isEmpty()
                                    && !finalChoices.contains(choice)) {
                                finalChoices.add(choice);
                            }
                        }
                    }
                    float[] confidences =
                            results.getFloatArray(SpeechRecognizer.CONFIDENCE_SCORES);
                    ArrayList<String> fallbackPartials = new ArrayList<>(partialChoices);
                    String candidate = chooseBestCandidate(
                            finalChoices.isEmpty() ? fallbackPartials : finalChoices
                    );
                    float confidence = confidenceForCandidate(
                            candidate,
                            finalChoices,
                            confidences
                    );
                    String normalizedCandidate = normalizeForEcho(candidate);
                    boolean incomplete = isIncompleteRecognition(normalizedCandidate);
                    String rejection = candidate.isEmpty()
                            ? "empty"
                            : incomplete
                            ? "incomplete"
                            : confidence >= 0f && confidence < LOW_COMMAND_CONFIDENCE
                            ? "low_confidence"
                            : "";
                    SageDiagnostics.recognitionDecision(
                            SageVoiceService.this,
                            finalChoices.toString(),
                            candidate,
                            confidence,
                            normalizedCandidate,
                            "",
                            rejection
                    );
                    destroyCommandRecognizer();
                    commandBusyRetries = 0;
                    if (!candidate.isEmpty()
                            && !rejection.isEmpty()
                            && commandQualityRetries < MAX_COMMAND_QUALITY_RETRIES
                            && isConversationOpen()
                            && !stopRequested
                            && !speaking) {
                        commandQualityRetries++;
                        broadcastStatus("I only caught part of that — listening once more");
                        updateNotification("Listening once more for the complete command");
                        startCommandRecognition(250L, true);
                    } else if (!candidate.isEmpty()) {
                        commandQualityRetries = 0;
                        handleCommand(candidate);''',
    "prefer final recognition and bounded retry",
)
replace_once(
    voice,
    '''    private int scoreCommandCandidate(String choice, int index) {''',
    '''    private float confidenceForCandidate(
            String candidate,
            ArrayList<String> finalChoices,
            float[] confidences
    ) {
        if (candidate == null || finalChoices == null || confidences == null) {
            return -1f;
        }
        for (int index = 0; index < finalChoices.size() && index < confidences.length; index++) {
            if (candidate.equals(finalChoices.get(index))) {
                return confidences[index];
            }
        }
        return -1f;
    }

    private boolean isIncompleteRecognition(String normalized) {
        if (normalized == null || normalized.isEmpty()) {
            return true;
        }
        int wordCount = normalized.split(" ").length;
        return isIncompleteCommandStem(normalized)
                || (wordCount == 1 && containsCommandCue(normalized));
    }

    private int scoreCommandCandidate(String choice, int index) {''',
    "speech confidence helpers",
)
replace_once(
    voice,
    '''        SageDiagnostics.recordHeard(this, cleaned);
        broadcastLine("You", cleaned);''',
    '''        SageDiagnostics.recordHeard(this, cleaned);
        SageDiagnostics.recognitionDecision(
                this,
                "[" + cleaned + "]",
                cleaned,
                -1f,
                normalizeForEcho(cleaned),
                "command_engine",
                ""
        );
        broadcastLine("You", cleaned);''',
    "selected command diagnostics",
)
replace_once(
    voice,
    '''        if (isLikelySelfEcho(cleaned)) {
            SageDiagnostics.echoRejected(this, cleaned);''',
    '''        if (isLikelySelfEcho(cleaned)) {
            SageDiagnostics.recognitionDecision(
                    this,
                    "[" + cleaned + "]",
                    cleaned,
                    -1f,
                    normalizeForEcho(cleaned),
                    "",
                    "speaker_echo"
            );
            SageDiagnostics.echoRejected(this, cleaned);''',
    "speech echo rejection diagnostics",
)

# Memory: separate note storage from phrase learning and make follow-up state one-shot.
(JAVA / "SageMemoryStore.java").write_text(
    '''package com.pineapple.sage;

import android.content.Context;
import android.content.SharedPreferences;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

final class SageMemoryStore {
    enum SaveResult { SAVED, DUPLICATE, FAILED }

    private static final String PREFS = "sage_state";
    private static final String ITEMS = "memory_items";
    private static final String LAST = "last_saved_memory";
    private static final String SEPARATOR = "\\t";

    private SageMemoryStore() {
    }

    static SaveResult save(Context context, String input) {
        String value = clean(input).replaceFirst("(?i)^that\\\\s+", "");
        if (value.isEmpty()) {
            return SaveResult.FAILED;
        }
        SharedPreferences preferences =
                context.getSharedPreferences(PREFS, Context.MODE_PRIVATE);
        Set<String> current = new HashSet<>(
                preferences.getStringSet(ITEMS, new HashSet<>())
        );
        String key = normalize(value);
        for (String entry : current) {
            if (normalize(decode(entry)).equals(key)) {
                preferences.edit().putString(LAST, decode(entry)).apply();
                return SaveResult.DUPLICATE;
            }
        }
        current.add(key + SEPARATOR + value);
        boolean saved = preferences.edit()
                .putStringSet(ITEMS, current)
                .putString(LAST, value)
                .commit();
        return saved ? SaveResult.SAVED : SaveResult.FAILED;
    }

    static String recallLast(Context context) {
        return context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
                .getString(LAST, "");
    }

    static List<String> recallAll(Context context) {
        Set<String> stored = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
                .getStringSet(ITEMS, new HashSet<>());
        List<String> items = new ArrayList<>();
        if (stored != null) {
            for (String entry : stored) {
                String value = decode(entry);
                if (!value.isEmpty() && !items.contains(value)) {
                    items.add(value);
                }
            }
        }
        items.sort(String.CASE_INSENSITIVE_ORDER);
        return items;
    }

    private static String decode(String entry) {
        if (entry == null) return "";
        int split = entry.indexOf(SEPARATOR);
        return clean(split >= 0 ? entry.substring(split + 1) : entry);
    }

    private static String normalize(String value) {
        return clean(value).toLowerCase(Locale.US)
                .replaceAll("[^a-z0-9 ]", " ")
                .replaceAll("\\\\s+", " ")
                .trim();
    }

    private static String clean(String value) {
        return value == null ? "" : value.trim().replaceAll("\\\\s+", " ");
    }
}
'''
)
replace_once(
    command,
    '''        if (shouldReplaceActionFollowUp(pendingAction, lower)) {
            pendingAction = "";
        }

        if (!pendingAction.isEmpty()) {''',
    '''        if (pendingAction.equals("remember_item")) {
            pendingAction = "";
            if (isAny(lower, "cancel", "never mind", "nevermind")) {
                SageDiagnostics.memoryEvent(context, "remember follow-up cancelled");
                return new Result("Okay. I did not save anything.");
            }
            return remember(raw);
        }

        if (shouldReplaceActionFollowUp(pendingAction, lower)) {
            pendingAction = "";
        }

        if (!pendingAction.isEmpty()) {''',
    "memory one-shot follow-up",
)
replace_once(
    command,
    '''        if (lower.startsWith("remember ")) {
            return remember(raw.substring(9));
        }
        if (lower.startsWith("note ")) {
            return remember(raw.substring(5));
        }
        if (isAny(lower, "memory", "what do you remember", "read my notes")) {
            return recall();
        }''',
    '''        if (isAny(lower, "remember", "remember something", "save a memory")) {
            pendingAction = "remember_item";
            return new Result("What should I remember?");
        }
        if (lower.startsWith("remember ")) {
            return remember(raw.substring(9));
        }
        if (lower.startsWith("note ")) {
            return remember(raw.substring(5));
        }
        if (isAny(
                lower,
                "what did i ask you to remember",
                "what did i tell you to remember",
                "what was the last thing i asked you to remember"
        )) {
            return recallLast();
        }
        if (isAny(lower, "memory", "what do you remember", "read my notes")) {
            return recall();
        }''',
    "memory commands and last recall",
)
replace_once(
    command,
    '''    private Result remember(String item) {
        String value = clean(item);
        if (value.isEmpty()) {
            return new Result("What should I remember?");
        }
        Set<String> saved = new HashSet<>(preferences.getStringSet("memory_items", new HashSet<>()));
        saved.add(value);
        boolean stored = preferences.edit().putStringSet("memory_items", saved).commit();
        return new Result(stored
                ? "I saved that in my memory."
                : "I heard that, but Android did not save it. Please try again.");
    }

    private Result recall() {
        Set<String> saved = preferences.getStringSet("memory_items", new HashSet<>());
        if (saved == null || saved.isEmpty()) {
            return new Result("I do not have any saved notes yet.");
        }
        List<String> items = new ArrayList<>(saved);
        return new Result("I remember: " + String.join(". ", items));
    }''',
    '''    private Result remember(String item) {
        String value = clean(item);
        if (value.isEmpty()) {
            pendingAction = "remember_item";
            return new Result("What should I remember?");
        }
        SageMemoryStore.SaveResult result = SageMemoryStore.save(context, value);
        if (result == SageMemoryStore.SaveResult.SAVED) {
            SageDiagnostics.memoryEvent(context, "saved once: " + value);
            return new Result("I saved that in my memory.");
        }
        if (result == SageMemoryStore.SaveResult.DUPLICATE) {
            SageDiagnostics.memoryEvent(context, "duplicate ignored: " + value);
            return new Result("I already remember that.");
        }
        SageDiagnostics.memoryEvent(context, "save failed: " + value);
        return new Result("I heard that, but Android did not save it. Please try again.");
    }

    private Result recallLast() {
        String last = SageMemoryStore.recallLast(context);
        return last.isEmpty()
                ? new Result("You have not asked me to remember anything yet.")
                : new Result("You asked me to remember: " + last + ".");
    }

    private Result recall() {
        List<String> items = SageMemoryStore.recallAll(context);
        if (items.isEmpty()) {
            return new Result("I do not have any saved notes yet.");
        }
        return new Result("I remember: " + String.join(". ", items));
    }''',
    "persistent deduplicated memory",
)

# Appearance controls and safe persisted document background.
(JAVA / "SageAppearance.java").write_text(
    '''package com.pineapple.sage;

import android.content.Context;
import android.content.SharedPreferences;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.graphics.drawable.BitmapDrawable;
import android.graphics.drawable.ColorDrawable;
import android.graphics.drawable.GradientDrawable;
import android.graphics.drawable.LayerDrawable;
import android.net.Uri;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ScrollView;
import android.widget.TextView;

import java.io.InputStream;

final class SageAppearance {
    static final String PREFS = "sage_state";
    static final String KEY_MODE = "appearance_mode";
    static final String KEY_BACKGROUND_URI = "appearance_background_uri";
    static final String KEY_BACKGROUND_INTENSITY = "appearance_background_intensity";
    static final String MODE_DARK = "dark";
    static final String MODE_DIM = "dim";
    static final String MODE_BLACK = "black";

    private SageAppearance() {
    }

    static String mode(Context context) {
        return context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
                .getString(KEY_MODE, MODE_DARK);
    }

    static void setMode(Context context, String mode) {
        context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
                .edit().putString(KEY_MODE, mode).apply();
    }

    static int intensity(Context context) {
        return context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
                .getInt(KEY_BACKGROUND_INTENSITY, 35);
    }

    static void setIntensity(Context context, int value) {
        context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
                .edit().putInt(KEY_BACKGROUND_INTENSITY, Math.max(0, Math.min(100, value)))
                .apply();
    }

    static void setBackground(Context context, Uri uri) {
        context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
                .edit().putString(KEY_BACKGROUND_URI, uri == null ? "" : uri.toString())
                .apply();
    }

    static void apply(Context context, ScrollView scroll, View root) {
        String mode = mode(context);
        int base = mode.equals(MODE_BLACK)
                ? Color.BLACK
                : mode.equals(MODE_DIM)
                ? Color.rgb(32, 35, 42)
                : Color.rgb(17, 24, 39);
        scroll.setBackgroundColor(base);
        String savedUri = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
                .getString(KEY_BACKGROUND_URI, "");
        if (savedUri != null && !savedUri.isEmpty()) {
            try (InputStream input =
                         context.getContentResolver().openInputStream(Uri.parse(savedUri))) {
                Bitmap bitmap = BitmapFactory.decodeStream(input);
                if (bitmap != null) {
                    BitmapDrawable image =
                            new BitmapDrawable(context.getResources(), bitmap);
                    image.setGravity(android.view.Gravity.FILL);
                    int intensity = intensity(context);
                    int darkness = 255 - Math.round(intensity * 1.7f);
                    darkness = Math.max(70, Math.min(235, darkness));
                    scroll.setBackground(new LayerDrawable(new android.graphics.drawable.Drawable[]{
                            image,
                            new ColorDrawable(Color.argb(darkness, 0, 0, 0))
                    }));
                } else {
                    setBackground(context, null);
                    scroll.setBackgroundColor(base);
                    SageDiagnostics.appendEvent(
                            context,
                            "APPEARANCE",
                            "Unreadable background image cleared safely"
                    );
                }
            } catch (Exception error) {
                setBackground(context, null);
                SageDiagnostics.appendEvent(
                        context,
                        "APPEARANCE",
                        "Missing background image cleared safely"
                );
            }
        }
        styleTree(root, mode);
    }

    private static void styleTree(View view, String mode) {
        int text = Color.rgb(245, 247, 250);
        int secondary = Color.rgb(209, 213, 219);
        int panel = mode.equals(MODE_BLACK)
                ? Color.rgb(10, 10, 10)
                : mode.equals(MODE_DIM)
                ? Color.rgb(48, 52, 61)
                : Color.rgb(31, 41, 55);
        if (view instanceof Button) {
            Button button = (Button) view;
            button.setTextColor(text);
            GradientDrawable background = new GradientDrawable();
            background.setColor(Color.rgb(55, 65, 81));
            background.setCornerRadius(18f);
            background.setStroke(1, Color.rgb(107, 114, 128));
            button.setBackground(background);
        } else if (view instanceof EditText) {
            EditText edit = (EditText) view;
            edit.setTextColor(text);
            edit.setHintTextColor(Color.rgb(156, 163, 175));
            edit.setBackgroundColor(panel);
        } else if (view instanceof TextView) {
            TextView label = (TextView) view;
            label.setTextColor(label.getTextSize() >= 21f ? text : secondary);
            if (label.isTextSelectable()) {
                label.setBackgroundColor(Color.argb(235, Color.red(panel), Color.green(panel), Color.blue(panel)));
            } else {
                label.setBackgroundColor(Color.TRANSPARENT);
            }
        }
        if (view instanceof ViewGroup) {
            ViewGroup group = (ViewGroup) view;
            for (int index = 0; index < group.getChildCount(); index++) {
                styleTree(group.getChildAt(index), mode);
            }
        }
    }
}
'''
)
replace_once(
    main,
    '''import android.widget.ScrollView;
import android.widget.TextView;''',
    '''import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.TextView;''',
    "appearance SeekBar import",
)
replace_once(
    main,
    '''    private static final int BRAIN_MODEL_FILE_PICKER = 44;''',
    '''    private static final int BRAIN_MODEL_FILE_PICKER = 44;
    private static final int BACKGROUND_IMAGE_FILE_PICKER = 45;
    private static final long[] OVERLAY_TIMEOUT_VALUES = {
            15000L, 30000L, 60000L, 120000L, -1L
    };
    private static final String[] OVERLAY_TIMEOUT_LABELS = {
            "15 seconds", "30 seconds", "60 seconds", "2 minutes",
            "Persistent until action"
    };''',
    "appearance and timeout constants",
)
replace_once(
    main,
    '''    private SageBrainManager brainManager;''',
    '''    private SageBrainManager brainManager;
    private ScrollView mainScroll;
    private View mainRoot;
    private Button appearanceModeButton;
    private Button overlayTimeoutButton;''',
    "appearance fields",
)
replace_once(
    main,
    '''        ScrollView scroll = new ScrollView(this);
        scroll.setFillViewport(true);
        scroll.setBackgroundColor(Color.rgb(247, 247, 252));''',
    '''        ScrollView scroll = new ScrollView(this);
        mainScroll = scroll;
        scroll.setFillViewport(true);
        scroll.setBackgroundColor(Color.rgb(17, 24, 39));''',
    "dark default scroll",
)
replace_once(
    main,
    '''        root.setOrientation(LinearLayout.VERTICAL);
        root.setPadding(pad, pad, pad, pad);''',
    '''        root.setOrientation(LinearLayout.VERTICAL);
        mainRoot = root;
        root.setPadding(pad, pad, pad, pad);''',
    "appearance root field",
)
replace_once(
    main,
    '''        root.addView(subtitle, matchWrap());

        statusText = new TextView(this);''',
    '''        root.addView(subtitle, matchWrap());

        TextView appearanceTitle = new TextView(this);
        appearanceTitle.setText("Appearance");
        appearanceTitle.setTextSize(23);
        appearanceTitle.setPadding(4, 18, 4, 4);
        root.addView(appearanceTitle, spaced());

        appearanceModeButton = makeButton("");
        appearanceModeButton.setOnClickListener(v -> cycleAppearanceMode());
        root.addView(appearanceModeButton, spacedSmall());

        Button chooseBackground = makeButton("Choose background image");
        chooseBackground.setOnClickListener(v -> chooseBackgroundImage());
        root.addView(chooseBackground, spacedSmall());

        Button clearBackground = makeButton("Clear background image");
        clearBackground.setOnClickListener(v -> {
            SageAppearance.setBackground(this, null);
            applyAppearance();
        });
        root.addView(clearBackground, spacedSmall());

        TextView intensityLabel = new TextView(this);
        intensityLabel.setText("Background intensity");
        intensityLabel.setTextSize(15);
        root.addView(intensityLabel, spacedSmall());

        SeekBar intensity = new SeekBar(this);
        intensity.setMax(100);
        intensity.setProgress(SageAppearance.intensity(this));
        intensity.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener() {
            @Override public void onProgressChanged(SeekBar bar, int value, boolean fromUser) {
                if (fromUser) {
                    SageAppearance.setIntensity(MainActivity.this, value);
                    applyAppearance();
                }
            }
            @Override public void onStartTrackingTouch(SeekBar bar) { }
            @Override public void onStopTrackingTouch(SeekBar bar) { }
        });
        root.addView(intensity, spacedSmall());

        overlayTimeoutButton = makeButton("");
        overlayTimeoutButton.setOnClickListener(v -> cycleOverlayTimeout());
        root.addView(overlayTimeoutButton, spacedSmall());
        refreshAppearanceLabels();

        statusText = new TextView(this);''',
    "appearance section",
)
replace_once(
    main,
    '''        return scroll;
    }

    @android.annotation.SuppressLint("UnspecifiedRegisterReceiverFlag")''',
    '''        SageAppearance.apply(this, scroll, root);
        return scroll;
    }

    private void refreshAppearanceLabels() {
        if (appearanceModeButton != null) {
            String mode = SageAppearance.mode(this);
            String label = mode.equals(SageAppearance.MODE_BLACK)
                    ? "Black"
                    : mode.equals(SageAppearance.MODE_DIM) ? "Dim" : "Dark";
            appearanceModeButton.setText("Appearance mode: " + label);
        }
        if (overlayTimeoutButton != null) {
            long current = getSharedPreferences("sage_state", Context.MODE_PRIVATE)
                    .getLong("number_overlay_timeout_ms", 60000L);
            int index = overlayTimeoutIndex(current);
            overlayTimeoutButton.setText(
                    "Screen number timeout: " + OVERLAY_TIMEOUT_LABELS[index]
            );
        }
    }

    private void cycleAppearanceMode() {
        String current = SageAppearance.mode(this);
        String next = current.equals(SageAppearance.MODE_DARK)
                ? SageAppearance.MODE_DIM
                : current.equals(SageAppearance.MODE_DIM)
                ? SageAppearance.MODE_BLACK
                : SageAppearance.MODE_DARK;
        SageAppearance.setMode(this, next);
        applyAppearance();
    }

    private void applyAppearance() {
        if (mainScroll != null && mainRoot != null) {
            SageAppearance.apply(this, mainScroll, mainRoot);
            refreshAppearanceLabels();
        }
    }

    private int overlayTimeoutIndex(long value) {
        for (int index = 0; index < OVERLAY_TIMEOUT_VALUES.length; index++) {
            if (OVERLAY_TIMEOUT_VALUES[index] == value) return index;
        }
        return 2;
    }

    private void cycleOverlayTimeout() {
        android.content.SharedPreferences preferences =
                getSharedPreferences("sage_state", Context.MODE_PRIVATE);
        long current = preferences.getLong("number_overlay_timeout_ms", 60000L);
        int next = (overlayTimeoutIndex(current) + 1) % OVERLAY_TIMEOUT_VALUES.length;
        preferences.edit()
                .putLong("number_overlay_timeout_ms", OVERLAY_TIMEOUT_VALUES[next])
                .apply();
        refreshAppearanceLabels();
    }

    private void chooseBackgroundImage() {
        Intent picker = new Intent(Intent.ACTION_OPEN_DOCUMENT);
        picker.addCategory(Intent.CATEGORY_OPENABLE);
        picker.setType("image/*");
        picker.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION
                | Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);
        startActivityForResult(picker, BACKGROUND_IMAGE_FILE_PICKER);
    }

    @android.annotation.SuppressLint("UnspecifiedRegisterReceiverFlag")''',
    "appearance methods",
)
replace_once(
    main,
    '''        if (requestCode == BRAIN_MODEL_FILE_PICKER) {
            importBrainModel(uri);
            return;
        }
        if (requestCode != UPDATE_FILE_PICKER) {''',
    '''        if (requestCode == BRAIN_MODEL_FILE_PICKER) {
            importBrainModel(uri);
            return;
        }
        if (requestCode == BACKGROUND_IMAGE_FILE_PICKER) {
            try {
                getContentResolver().takePersistableUriPermission(
                        uri,
                        Intent.FLAG_GRANT_READ_URI_PERMISSION
                );
            } catch (Exception ignored) {
            }
            SageAppearance.setBackground(this, uri);
            applyAppearance();
            return;
        }
        if (requestCode != UPDATE_FILE_PICKER) {''',
    "background picker result",
)
replace_once(
    main,
    '''        refreshBrainStatus();
        if (pendingUpdateUri != null''',
    '''        refreshBrainStatus();
        applyAppearance();
        if (pendingUpdateUri != null''',
    "appearance on resume",
)

# Keep the persisted "last memory" marker consistent with an explicit memory clear.
replace_once(
    command,
    '''        if (isAny(lower, "clear memory", "forget everything")) {
            preferences.edit().remove("memory_items").commit();
            return new Result("Memory cleared.");
        }''',
    '''        if (isAny(lower, "clear memory", "forget everything")) {
            preferences.edit()
                    .remove("memory_items")
                    .remove("last_saved_memory")
                    .commit();
            SageDiagnostics.memoryEvent(context, "memory cleared");
            return new Result("Memory cleared.");
        }''',
    "complete memory clear",
)

# Record wake candidates as raw input plus normalized matching decisions.
replace_once(
    voice,
    '''        if (!startsWithWakePhrase(normalized, finalResult)) {
            if (finalResult) {
                SageDiagnostics.wakeCandidateMissed(this, normalized);
            }
            return;
        }
        SageDiagnostics.recordHeard(this, normalized);''',
    '''        if (!startsWithWakePhrase(normalized, finalResult)) {
            if (finalResult) {
                SageDiagnostics.recognitionDecision(
                        this,
                        "[" + text + "]",
                        text,
                        -1f,
                        normalized,
                        "",
                        "wake_phrase_not_matched"
                );
                SageDiagnostics.wakeCandidateMissed(this, normalized);
            }
            return;
        }
        SageDiagnostics.recognitionDecision(
                this,
                "[" + text + "]",
                text,
                -1f,
                normalized,
                "wake_phrase",
                ""
        );
        SageDiagnostics.recordHeard(this, text.trim());''',
    "wake recognition diagnostics",
)

# Record whether the deterministic parser actually matched after routing.
replace_once(
    voice,
    '''        SageCommandEngine.Result result = commandEngine.execute(cleaned);
        if (!result.matched && brainManager != null && brainManager.canAnswer()) {''',
    '''        SageCommandEngine.Result result = commandEngine.execute(cleaned);
        SageDiagnostics.recognitionDecision(
                this,
                "[" + cleaned + "]",
                cleaned,
                -1f,
                normalizeForEcho(cleaned),
                result.matched ? "command_engine" : "",
                result.matched ? "" : "no_deterministic_match"
        );
        if (!result.matched && brainManager != null && brainManager.canAnswer()) {''',
    "command match diagnostics",
)

# 1.24.2 release identity.
text = build_gradle.read_text()
text, code_count = re.subn(
    r'versionCode\s*(?:=\s*)?\d+',
    'versionCode = 36',
    text,
    count=1,
)
text, name_count = re.subn(
    r'versionName\s*(?:=\s*)?["\'][^"\']+["\']',
    'versionName = "1.24.2"',
    text,
    count=1,
)
if code_count != 1 or name_count != 1:
    raise SystemExit(
        f"1.24.2 identity: expected one code and one name, got {code_count}/{name_count}"
    )
build_gradle.write_text(text)

for xml in (ROOT / "app/src/main").rglob("*.xml"):
    xml_text = xml.read_text()
    updated = re.sub(
        r'Sage Commander(?:\s+\d+\.\d+(?:\.\d+)?)?',
        'Sage Commander 1.24.2',
        xml_text,
    )
    if updated != xml_text:
        xml.write_text(updated)

print("Applied Sage Commander 1.24.2 overlay, speech, memory, and appearance update")
