from pathlib import Path
import re
import sys

ROOT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path('sage_build')
JAVA = ROOT / 'app/src/main/java/com/pineapple/sage'


def replace_once(path: Path, old: str, new: str, label: str) -> None:
    text = path.read_text()
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{label}: expected exactly one match, found {count}')
    path.write_text(text.replace(old, new, 1))

access = JAVA / 'SageAccessibilityService.java'
commands = JAVA / 'SageCommandEngine.java'
voice = JAVA / 'SageVoiceService.java'

replace_once(
    access,
    '    private static final long NUMBER_OVERLAY_TIMEOUT_MS = 25000L;\n'
    '    private static final long NUMBER_OVERLAY_EVENT_GRACE_MS = 650L;',
    '    private static final long NUMBER_OVERLAY_TIMEOUT_MS = 120000L;\n'
    '    private static final long NUMBER_OVERLAY_EVENT_GRACE_MS = 2500L;',
    'overlay timing constants',
)

replace_once(
    access,
'''        String eventPackage = event.getPackageName() == null
                ? ""
                : event.getPackageName().toString();
        int eventWindowId = event.getWindowId();
        boolean differentPackage = eventWindowId >= 0
                && !numberedPackageName.isEmpty()
                && !eventPackage.isEmpty()
                && !numberedPackageName.equals(eventPackage);
        boolean differentWindow = numberedWindowId >= 0
                && eventWindowId >= 0
                && numberedWindowId != eventWindowId;
        int type = event.getEventType();
        boolean screenMoved = type == AccessibilityEvent.TYPE_VIEW_SCROLLED
                || type == AccessibilityEvent.TYPE_VIEW_CLICKED
                || type == AccessibilityEvent.TYPE_WINDOW_STATE_CHANGED
                || type == AccessibilityEvent.TYPE_WINDOWS_CHANGED;
        if (differentPackage || differentWindow || screenMoved) {
            clearNumberOverlayInternal();
        }''',
'''        String eventPackage = event.getPackageName() == null
                ? ""
                : event.getPackageName().toString();
        if (!eventPackage.isEmpty() && eventPackage.equals(getPackageName())) {
            // Accessibility-overlay window notifications are generated by Sage itself.
            return;
        }
        int eventWindowId = event.getWindowId();
        boolean differentPackage = !numberedPackageName.isEmpty()
                && !eventPackage.isEmpty()
                && !numberedPackageName.equals(eventPackage);
        boolean differentWindow = !differentPackage
                && numberedWindowId >= 0
                && eventWindowId >= 0
                && numberedWindowId != eventWindowId;
        int type = event.getEventType();
        boolean deliberateMovement = type == AccessibilityEvent.TYPE_VIEW_SCROLLED
                || type == AccessibilityEvent.TYPE_VIEW_CLICKED;
        // YouTube emits window/content churn while thumbnails finish loading. Keep the
        // numbered choices through that harmless churn; clear only after real navigation.
        if (differentPackage || differentWindow || deliberateMovement) {
            clearNumberOverlayInternal();
        }''',
    'overlay event policy',
)

replace_once(
    access,
'''        ScreenTarget currentTarget = resolveCurrentTarget(
                savedTarget,
                currentTargets,
                metrics.widthPixels
        );
        service.clearNumberOverlayInternal();
        return currentTarget != null && service.clickNodeOrTap(currentTarget.node);''',
'''        ScreenTarget currentTarget = resolveCurrentTarget(
                savedTarget,
                currentTargets,
                metrics.widthPixels
        );
        boolean opened = currentTarget != null
                && service.clickNodeOrTap(currentTarget.node, currentTarget.bounds);
        if (opened) {
            service.clearNumberOverlayInternal();
        }
        return opened;''',
    'numbered target click lifecycle',
)

replace_once(
    access,
'''    private boolean clickNodeOrTap(AccessibilityNodeInfo node) {
        AccessibilityNodeInfo current = node;
        AccessibilityNodeInfo bestBoundsNode = node;
        while (current != null) {
            Rect bounds = new Rect();
            current.getBoundsInScreen(bounds);
            if (!bounds.isEmpty()) {
                bestBoundsNode = current;
            }
            if (current.isClickable() && current.performAction(AccessibilityNodeInfo.ACTION_CLICK)) {
                return true;
            }
            current = current.getParent();
        }
        if (node.performAction(AccessibilityNodeInfo.ACTION_CLICK)) {
            return true;
        }
        return tapNodeCenter(bestBoundsNode);
    }''',
'''    private boolean clickNodeOrTap(AccessibilityNodeInfo node) {
        Rect fallbackBounds = new Rect();
        if (node != null) {
            node.getBoundsInScreen(fallbackBounds);
        }
        return clickNodeOrTap(node, fallbackBounds);
    }

    private boolean clickNodeOrTap(AccessibilityNodeInfo node, Rect fallbackBounds) {
        if (node == null) {
            return false;
        }
        AccessibilityNodeInfo current = node;
        while (current != null) {
            if (current.isClickable()
                    && current.performAction(AccessibilityNodeInfo.ACTION_CLICK)) {
                return true;
            }
            current = current.getParent();
        }
        if (node.performAction(AccessibilityNodeInfo.ACTION_CLICK)) {
            return true;
        }
        // Never fall back to an outer container or the screen center. The marker's
        // revalidated bounds are the safest coordinate when accessibility click fails.
        return tapBounds(fallbackBounds);
    }''',
    'coordinate fallback',
)

replace_once(
    access,
'''        String savedText = normalizeTargetText(saved.text);
        ScreenTarget best = null;
        int bestScore = Integer.MIN_VALUE;
        int nearbyDistance = Math.max(72, screenWidth / 14);
        for (ScreenTarget current : currentTargets) {
            String currentText = normalizeTargetText(current.text);
            int score = 0;
            if (!savedText.isEmpty() && savedText.equals(currentText)) {
                score += 120;
            } else if (savedText.length() >= 5
                    && currentText.length() >= 5
                    && (savedText.contains(currentText) || currentText.contains(savedText))) {
                score += 70;
            }
            Rect overlap = new Rect(saved.bounds);
            if (overlap.intersect(current.bounds)) {
                score += 45;
            }
            int distance = Math.abs(saved.bounds.centerX() - current.bounds.centerX())
                    + Math.abs(saved.bounds.centerY() - current.bounds.centerY());
            if (distance <= nearbyDistance) {
                score += 35;
            } else if (distance <= nearbyDistance * 2) {
                score += 15;
            }
            if (score > bestScore) {
                best = current;
                bestScore = score;
            }
        }
        return bestScore >= 35 ? best : null;''',
'''        String savedText = normalizeTargetText(saved.text);
        ScreenTarget best = null;
        int bestScore = Integer.MIN_VALUE;
        int nearbyDistance = Math.max(72, screenWidth / 14);
        for (ScreenTarget current : currentTargets) {
            String currentText = normalizeTargetText(current.text);
            int score = 0;
            boolean identityMatched = saved.node != null
                    && current.node != null
                    && saved.node.equals(current.node);
            if (identityMatched) {
                score += 160;
            } else if (!savedText.isEmpty() && savedText.equals(currentText)) {
                identityMatched = true;
                score += 120;
            } else if (savedText.length() >= 5
                    && currentText.length() >= 5
                    && (savedText.contains(currentText) || currentText.contains(savedText))) {
                identityMatched = true;
                score += 80;
            }
            if (!identityMatched) {
                // Geometry alone must never turn a refreshed card into the old choice.
                continue;
            }
            Rect overlap = new Rect(saved.bounds);
            if (overlap.intersect(current.bounds)) {
                score += 45;
            }
            int distance = Math.abs(saved.bounds.centerX() - current.bounds.centerX())
                    + Math.abs(saved.bounds.centerY() - current.bounds.centerY());
            if (distance <= nearbyDistance) {
                score += 35;
            } else if (distance <= nearbyDistance * 2) {
                score += 15;
            }
            if (score > bestScore) {
                best = current;
                bestScore = score;
            }
        }
        return bestScore >= 80 ? best : null;''',
    'target identity revalidation',
)

replace_once(
    access,
'''        targets.sort((left, right) -> {
            int rowTolerance = Math.max(32, screenHeight / 28);
            int rowDifference = left.bounds.centerY() - right.bounds.centerY();
            if (Math.abs(rowDifference) <= rowTolerance) {
                return Integer.compare(left.bounds.left, right.bounds.left);
            }
            return Integer.compare(left.bounds.top, right.bounds.top);
        });''',
'''        final int rowHeight = Math.max(32, screenHeight / 28);
        targets.sort((left, right) -> {
            int leftRow = Math.max(0, left.bounds.centerY()) / rowHeight;
            int rightRow = Math.max(0, right.bounds.centerY()) / rowHeight;
            int rowComparison = Integer.compare(leftRow, rightRow);
            if (rowComparison != 0) {
                return rowComparison;
            }
            int horizontalComparison = Integer.compare(left.bounds.left, right.bounds.left);
            if (horizontalComparison != 0) {
                return horizontalComparison;
            }
            return Integer.compare(left.bounds.top, right.bounds.top);
        });''',
    'transitive target ordering',
)

replace_once(
    commands,
'''        if (SageAccessibilityService.hasNumberOverlay() && numberedChoice > 0
                && (isStandaloneNumber(lower) || containsAnyPhrase(lower, "number", "click", "tap", "pick", "choose", "select", "open"))) {''',
'''        if (SageAccessibilityService.hasNumberOverlay() && numberedChoice > 0
                && (pendingAction.equals("screen_number")
                || isStandaloneNumber(lower)
                || containsAnyPhrase(lower, "number", "click", "tap", "pick", "choose",
                "select", "open", "play", "video", "item", "choice"))) {''',
    'spoken numbered selection phrases',
)

replace_once(
    commands,
'''        if (pendingAction.equals("screen_number")) {
            pendingAction = "";
            SageAccessibilityService.clearNumberOverlay();
            if (numberedChoice > 0) {
                return new Result("Those screen numbers already cleared. Say show video numbers to make a fresh set.");
            }
        }''',
'''        if (pendingAction.equals("screen_number")) {
            if (containsAnyPhrase(lower, "clear numbers", "clear the numbers", "cancel numbers",
                    "never mind", "nevermind", "cancel")) {
                pendingAction = "";
                SageAccessibilityService.clearNumberOverlay();
                return Result.quiet("Screen numbers cleared.");
            }
            if (SageAccessibilityService.hasNumberOverlay()) {
                return new Result("Say a red number, or say clear numbers.");
            }
            pendingAction = "";
        }''',
    'keep number follow-up alive',
)

replace_once(
    commands,
'''For screen choices, say play the second video. If I need red numbers, they clear automatically.''',
'''For screen choices, say play the second video. Red numbers stay until you choose, move the screen, or clear them.''',
    'help text',
)

replace_once(
    commands,
'''        String itemName = type.equals("video") ? "videos" : "things";
        return new Result("I numbered " + count + " " + itemName
                + " from top to bottom. Say the red number you want. The numbers clear automatically.");''',
'''        return new Result("Numbers ready. Say the red number.");''',
    'short number prompt',
)

replace_once(
    voice,
'''        for (String soundalike : SAFE_PREFIXED_WAKE_SOUNDALIKES) {
            if (normalized.equals(soundalike)) {
                return true;
            }
        }
        if (!finalResult) {
            return false;
        }
        for (String alias : EXACT_WAKE_ALIASES) {''',
'''        if (!finalResult) {
            return false;
        }
        for (String soundalike : SAFE_PREFIXED_WAKE_SOUNDALIKES) {
            if (normalized.equals(soundalike)) {
                return true;
            }
        }
        for (String alias : EXACT_WAKE_ALIASES) {''',
    'final-only weak wake aliases',
)

replace_once(
    voice,
'''        SageMediaResponseStore.Entry voiceResponse =
                SageMediaResponseStore.find(preferences, cleaned);
        if (voiceResponse != null) {
            playVoiceResponse(voiceResponse);
            return;
        }''',
'''        SageMediaResponseStore.Entry voiceResponse =
                SageMediaResponseStore.find(preferences, cleaned);
        if (voiceResponse != null) {
            commandEngine.cancelFollowUp();
            playVoiceResponse(voiceResponse);
            return;
        }''',
    'custom response cancels stale follow-up',
)

text = voice.read_text()
pattern = re.compile(
    r'        if \(brainManager != null\n'
    r'                && brainManager\.canAnswer\(\)\n'
    r'                && isOpenEndedBrainRequest\(cleaned\)\) \{.*?'
    r'        SageCommandEngine\.Result result = commandEngine\.execute\(cleaned\);',
    re.DOTALL,
)
replacement = (
    '        // Always let deterministic commands, learned aliases, and pending follow-ups run first.\n'
    '        SageCommandEngine.Result result = commandEngine.execute(cleaned);'
)
text, count = pattern.subn(replacement, text, count=1)
if count != 1:
    raise SystemExit(f'deterministic routing before brain: expected one match, found {count}')
voice.write_text(text)

replace_once(
    voice,
'''        recognizerIntent.putExtra(RecognizerIntent.EXTRA_SPEECH_INPUT_MINIMUM_LENGTH_MILLIS, 1200L);
        recognizerIntent.putExtra(RecognizerIntent.EXTRA_SPEECH_INPUT_COMPLETE_SILENCE_LENGTH_MILLIS, 850L);
        recognizerIntent.putExtra(RecognizerIntent.EXTRA_SPEECH_INPUT_POSSIBLY_COMPLETE_SILENCE_LENGTH_MILLIS, 600L);''',
'''        recognizerIntent.putExtra(RecognizerIntent.EXTRA_SPEECH_INPUT_MINIMUM_LENGTH_MILLIS, 800L);
        recognizerIntent.putExtra(RecognizerIntent.EXTRA_SPEECH_INPUT_COMPLETE_SILENCE_LENGTH_MILLIS, 650L);
        recognizerIntent.putExtra(RecognizerIntent.EXTRA_SPEECH_INPUT_POSSIBLY_COMPLETE_SILENCE_LENGTH_MILLIS, 400L);''',
    'command recognition latency',
)

# Keep the permanent package/signing identity and advance the in-place update version.
build_gradle = ROOT / 'app/build.gradle.kts'
text = build_gradle.read_text()
text, app_count = re.subn(
    r'applicationId\s*=\s*"[^"]+"',
    'applicationId = "com.pineapple.sagecommander.stable"',
    text,
    count=1,
)
text, code_count = re.subn(r'versionCode\s*=\s*\d+', 'versionCode = 31', text, count=1)
text, name_count = re.subn(r'versionName\s*=\s*"[^"]+"', 'versionName = "1.21"', text, count=1)
if app_count != 1 or code_count != 1 or name_count != 1:
    raise SystemExit(
        f'permanent identity: app={app_count}, code={code_count}, name={name_count}'
    )

if 'com.alphacephei:vosk-android' not in text:
    dependency_lines = (
        '    implementation("net.java.dev.jna:jna:5.18.1@aar")\n'
        '    implementation("com.alphacephei:vosk-android:0.3.75@aar")\n'
    )
    match = re.search(r'dependencies\s*\{', text)
    if match:
        text = text[:match.end()] + '\n' + dependency_lines + text[match.end():]
    else:
        text = text.rstrip() + '\n\ndependencies {\n' + dependency_lines + '}\n'

if 'com.google.mlkit:translate' not in text:
    translation_dependencies = (
        '    implementation("com.google.mlkit:translate:17.0.3")\n'
        '    implementation("com.google.mlkit:language-id:17.0.6")\n'
    )
    match = re.search(r'dependencies\s*\{', text)
    if not match:
        raise SystemExit('dependencies block missing after Vosk insertion')
    text = text[:match.end()] + '\n' + translation_dependencies + text[match.end():]

if 'sagePermanentSigning' not in text:
    text = text.rstrip() + (
        '\n\nandroid {\n'
        '    signingConfigs {\n'
        '        create("sagePermanentSigning") {\n'
        '            storeFile = rootProject.file(System.getProperty("user.home") + "/.android/debug.keystore")\n'
        '            storePassword = "android"\n'
        '            keyAlias = "androiddebugkey"\n'
        '            keyPassword = "android"\n'
        '        }\n'
        '    }\n'
        '    buildTypes {\n'
        '        getByName("debug") {\n'
        '            signingConfig = signingConfigs.getByName("sagePermanentSigning")\n'
        '        }\n'
        '    }\n'
        '}\n'
    )
build_gradle.write_text(text)

manifest = ROOT / 'app/src/main/AndroidManifest.xml'
manifest_text = manifest.read_text()
for permission in (
    '<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />',
    '<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />',
):
    permission_name = permission.split('"')[1]
    if permission_name not in manifest_text:
        manifest_text = manifest_text.replace('<application', permission + '\n    <application', 1)
manifest.write_text(manifest_text)

for xml in (ROOT / 'app/src/main').rglob('*.xml'):
    xml_text = xml.read_text()
    updated = re.sub(
        r'Sage Commander(?:\s+\d+\.\d+)?',
        'Sage Commander 1.21',
        xml_text,
    )
    if updated != xml_text:
        xml.write_text(updated)

print('Applied Sage 1.21 stabilization and permanent update identity.')
